# Generated by Django 5.0.7 on 2025-01-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0015_alter_patient_histopath_details_and_more'),
        ('part_1', '0015_patient_histopath_details'),
    ]

    operations = [
    ]
