# Generated by Django 4.2.5 on 2025-01-01 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0016_merge_20250101_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Age cannot be negative')]),
        ),
    ]
