# Generated by Django 4.2.5 on 2025-01-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0018_alter_patient_gleason_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gleason_score',
            field=models.CharField(blank=True, choices=[('', 'Select Gleason Score'), ('<6', 'Less than 6'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text='Select the Gleason score', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='salivary_gland_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
