# Generated by Django 4.2.5 on 2025-01-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0019_alter_patient_gleason_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gleason_score',
            field=models.CharField(blank=True, choices=[('', '----------'), ('<6', 'Less than 6'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=2, null=True),
        ),
    ]
