# Generated by Django 4.2.5 on 2025-01-05 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0020_alter_patient_gleason_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='bp',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='ecog_score',
            field=models.IntegerField(choices=[(0, '0 - Fully active'), (1, '1 - Restricted but ambulatory'), (2, '2 - Ambulatory but unable to work'), (3, '3 - Limited self-care'), (4, '4 - Completely disabled'), (5, '5 - Dead')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='hr',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='pain_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
