# Generated by Django 4.2.5 on 2025-01-07 06:03

from django.db import migrations, models
import part_1.models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0022_alter_screening_platelet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='platelet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[part_1.models.Screening.validate_platelet_digits]),
        ),
    ]
