# Generated by Django 4.2.5 on 2025-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0024_alter_screening_platelet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='wbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
