# Generated by Django 4.2.5 on 2025-01-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_4', '0004_alter_followup_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='bone_scan_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='salivary_gland_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
