# Generated by Django 4.2.5 on 2025-01-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_4', '0005_alter_followup_bone_scan_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='platelet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
