# Generated by Django 4.2.5 on 2025-01-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_4', '0010_alter_followup_creatinine_alter_followup_hemoglobin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='alkaline_phosphatase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='bilirubins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='lactate_hydrogenase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='sgot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='sgpt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
