# Generated by Django 4.2.5 on 2025-01-05 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0008_alter_posttherapy_kidney_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttherapy',
            name='post_therapy_scan_hours',
            field=models.IntegerField(blank=True, help_text='Enter the number of hours (minimum 0)', null=True, validators=[django.core.validators.MinValueValidator(0, message='Scan hours cannot be negative')]),
        ),
    ]
