# Generated by Django 4.2.5 on 2025-01-05 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0010_alter_posttherapy_dosimetry_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttherapy',
            name='kidney_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='kidney_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='post_therapy_scan_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='salivary_gland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
