# Generated by Django 4.2.5 on 2025-01-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0011_alter_posttherapy_kidney_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttherapy',
            name='lesion_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='lesions',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
