# Generated by Django 4.2.5 on 2025-01-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0012_alter_posttherapy_lesion_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttherapy',
            name='dosimetry_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
