# Generated by Django 4.2.5 on 2025-01-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0005_alter_therapy_diastolic_alter_therapy_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='side_effects',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
